// flow-typed signature: 3fd60c3b9ee8df3149014a6986fac29d
// flow-typed version: <<STUB>>/tpl-api-helpers_v^0.1.4/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tpl-api-helpers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tpl-api-helpers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tpl-api-helpers/babel' {
  declare module.exports: any;
}

declare module 'tpl-api-helpers/sequelize/index' {
  declare module.exports: any;
}

declare module 'tpl-api-helpers/util/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tpl-api-helpers/babel.js' {
  declare module.exports: $Exports<'tpl-api-helpers/babel'>;
}
declare module 'tpl-api-helpers/index' {
  declare module.exports: $Exports<'tpl-api-helpers'>;
}
declare module 'tpl-api-helpers/index.js' {
  declare module.exports: $Exports<'tpl-api-helpers'>;
}
declare module 'tpl-api-helpers/sequelize/index.js' {
  declare module.exports: $Exports<'tpl-api-helpers/sequelize/index'>;
}
declare module 'tpl-api-helpers/util/index.js' {
  declare module.exports: $Exports<'tpl-api-helpers/util/index'>;
}
